FROM maven:3.9.11-eclipse-temurin-21 AS build
COPY src /src  
COPY pom.xml .  
RUN mvn clean package


FROM eclipse-temurin:21-jre
ARG JAR_FILE=target/hello.spring-0.0.1-SNAPSHOT.jar
COPY --from=build ${JAR_FILE} main.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/main.jar"]
