name: Java CI with Maven and Docker

on:
  push:
    branches: with_workflow_publish
  pull_request:
    branches: with_workflow_publish

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Docker Build
      run: docker build . --file Dockerfile --tag hello-spring:latest
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Push Image
      run: docker push gibeonufrn/hello-spring
      
